### ISSUE TITLE
Cannot use Kirby-builder plugin with Murby

### ISSUE THREAD

**Issue by isUnknown** [FNGR2911/murby#12]
Hi there,

It seems that Murby's server isn't compatible with the [kirby-builder plugin](https://github.com/TimOetting/kirby-builder). The panel display ```"The field type "XXX" does not exist"```. However, the plugin works with on a server launched with the command ```php -S localhost:8000 kirby/router.php```.

**Comment by Rychetsky** [comment]
@isUnknown I'm using Murby with the kirby-builder plugin without problems.

**Comment by isUnknown** [comment]
@Rychetsky Strange…

**Comment by FNGR2911** [comment]
@isUnknown Same here, I'm using the kirby-builder plugin without any problems. Does it work for you on another server? Like Apache?

Which version of PHP do you use on the CLI where you start the server?
