### ISSUE TITLE
feature request: reload for content changes (html, php, yml, etc. )

### ISSUE THREAD

**Issue by grommas** [FNGR2911/murby#2]
Are you planning to implement a live reload for content changes? (html, php, yml, etc. )

**Comment by FNGR2911** [comment]
Hi @grommas! Yes, I'll look what is possible with webpack, without open a second proxy like you have to with browsersync. Unfortunately it is not that easy with Webpack.

If you have any ideas or suggestions, feel free to reopen this Issue!

**Comment by moevbiz** [comment]
For php hot reloading, this seems to be working (just tested on a local Murby copy, thinking about making it into a Kirby plugin): https://github.com/felippe-regazio/php-hot-reloader
