### ISSUE TITLE
panel without images | startup with router.php

### ISSUE THREAD

**Issue by jhercher** [FNGR2911/murby#3]
Kudos for your great project!

The [Kirby docs](https://getkirby.com/docs/cookbook/setup/development-environment#php-s-built-in-server) suggest to startup the local PHP server with a reference to `kirby/router.php`:
```
php -S localhost:8000 kirby/router.php
``` 
The page will work without the router, but images are not shown in the panel. A click on the resource results in an error:
`The JSON response from the API could not be parsed. Please check your API connection.` 

`cd murby/web` and `php -S localhost:8282 kirby/router.php -t ../web` will show the images in the panel without errors.

package.json contains the local php server startup on line 6: 
```
	 "server": "php -S localhost:8282  -t web",
```  
A change to 
```
 "server": "php -S localhost:8282 web/kirby/router.php -t web",
```  
won't work.

I there a chance to startup the server with the `router.php`?

Cheers, Johannes

**Comment by FNGR2911** [comment]
Hi Johannes! You were right, the server command wasn't right. I changed it to the following:
```json
"server": "php -S localhost:8282 -t web web/kirby/router.php"
```
This works for me now. Could you test it? I updated the repo.

**Comment by jhercher** [comment]
Hi! I cloned/installed the repo and started it with `npm run start`. The thumbnails and images are not shown in the first place. 
Then I started murby with `php -S localhost:8000 kirby/router.php` and uploaded some images. Now, I was able to see the thumbs also on `http://localhost:8282/panel/pages/test`. Unfortunately, they still can't be viewed due to the  failed JSON response mentioned above.

Looking into the browser console I see a php error:  
```
Warning:  include(../vendor/autoload.php): failed to open stream: No such file or directory in /Volumes/…/testmurby/murby/web/index.php</b> on line <b>3</b><br />

Warning:  include(): Failed opening '../vendor/autoload.php' for inclusion (include_path='.:') in /Volumes/…/testmurby/murby/web/index.php</b> on line <b>3</b><br />
Fatal error:  Uncaught Error: Class 'Kirby' not found in /Volumes/…/murby/web/index.php:5
Stack trace:
#0 /Volumes/…/murby/web/kirby/router.php(12): include()
#1 {main}
  thrown in <b>/Volumes/…/murby/web/index.php</b> on line <b>5</b><br />

```  
I hope this helps.

**Comment by Splendorr** [comment]
Hi, I really like the concept for this and it almost works! However, I'm having this same problem in my test installation of murby. Images in the panel are broken, and clicking on one gives the API error. 

The [Kirby troubleshooting page](https://getkirby.com/docs/guide/troubleshooting/panel#panel-error-messages) says these errors can happen "if HTTP PATCH requests are disabled." I don't know how to tell if that's happening, and have never had this problem running other Kirby projects locally through PHP or with a gulp script.

In the page console, I see these errors:

```
The stylesheet http://localhost:8282/media/plugins/index.css?0 was not loaded because its MIME type, “text/html”, is not “text/css”. site
The script from “http://localhost:8282/media/plugins/index.js?0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
site
SyntaxError: expected expression, got '<'
index.js:1
TypeError: "NetworkError when attempting to fetch resource." app.js:1:255682
```
I'm running macOS 10.14.6 and running npm from iTerm 2.

**Comment by Splendorr** [comment]
Further, if I do as @jhercher said and cd into web then run `php -S localhost:8000 kirby/router.php`, I'm able to upload an image and click on it to view. However, when I try to add an image to a page field, it briefly flashes up and then resets the page. That's another symptom the panel troubleshooting page says could be a PATCH error. I've just never encountered this before with a vanilla Kirby installation, so I'm stumped!

I tried messing with folder permissions, which can be a problem on a server, but that didn't seem to matter. As far as I can tell, uploading an image creates all the right files in the content and media folders, and they even show up in templates. But I need the panel to function properly before I can hand this over to a client.

**Comment by Splendorr** [comment]
Returning a month later, I *think* this problem was solved by updating from php 7.1 to 7.4. However, I'm encountering other errors, including users not creating properly (.htpassword has the password in plain text, and the login screen says password doesn't match) that are preventing me from pursuing this further or confirming that this is a real solution. Anecdotally, I was able to upload images and see them in the panel using PHP 7.4. However, first I had to copy an account from another standard Kirby installation that had a properly-hashed password to log in to the panel at all.

**Comment by jhercher** [comment]
After all I found a solution.  Looking into `./web/index.php` I changed:
`include '../vendor/autoload.php'; `
to
`require 'kirby/bootstrap.php';`

I also updated from php 7.1 to 7.3. Initially there was an error in the panel  `JIT compilation failed: no more memory` but I was able to fix it by disabling [PHP PCRE JIT in the php.ini](https://stackoverflow.com/questions/53690624/errors-installing-composer-on-macos-jit-compilation-failed). So far I can see all images in the panel. Some older uploads seem to be resistant to change, but uploading new images works. I guess thats another topic.

@Splendorr: The [Kirby Quickstart](https://getkirby.com/docs/guide/quickstart) recommends PHP 7.3, so maybe you could give that a try?!

**Comment by BenGamma** [comment]
I there 👋,

I run into the same problem, no images loaded on either site and panel. My PHP version is 7.3.

Turned out it was link to the fact that my `.htaccess` file was ignored using the php server command `php -S localhost:8282 -t web web/kirby/router.php`. Couldn't really figured out why 🤷‍♂ 

I fixed it by putting my project into a MAMP server directory and run `npm run dev` to compile and live reload.

Hope that will help others that could run into the same issue !

**Comment by FNGR2911** [comment]
Hey everybody! I updated the Kirby Core to ^3.3 and my local PHP version to 7.4. I tested everything again, and now it seems that the problem with the missing images is gone (it works on my machine ;)).

Please feel free to test the latest version. I also updated all npm dependencies to the latest versions. 💥
